### PR TITLE
Remove the navbar on the left

### PR DESCRIPTION
**Pull request by rikhuijzer**
There wasn't really much point to the navigation bar on the left because the hierarchy of this project is pretty straightforward:

- home
  - model 1
  - model 2
  - model 3
  - ...

Giving each model a separate entry in the navigation bar would become very cluttered because we have about 30 model pages and the aim is to go even higher. For comparison, R with data science has [30 pages](https://r4ds.had.co.nz/introduction.html) and I don't see how they could have fit more. 

So, this PR removes the navigation bar on the left and replaces it with a navigation bar on top. The bar on the top has only one button: "TuringModels" which brings the user back to the homepage.

### CODE REVIEW

**Comment by goedman** [comment]
Great, will you merge it as v2.0? Should we add a badge pointing to the docs, next to the build badge?

We can probably also remove the old Travis related files, but that's a detail.

Thanks for all your work!

**Comment by rikhuijzer** [comment]
> Great, will you merge it as v2.0? Should we add a badge pointing to the docs, next to the build badge?

Yes, that could be nice. I'll add it :+1: 

I plan to merge #56 as v2.0. After this layout change, I'm almost there. There are still some scripts in `scripts/10` and `scripts/12` which I need to convert to make them consistent with the other scripts.

> We can probably also remove the old Travis related files, but that's a detail.

Will do :+1: 

> Thanks for all your work!

Thanks!

**Comment by goedman** [comment]
Once you're done I wonder if I should rework StatisticalRethinkingTuring to work off identical formulated models.

**Comment by rikhuijzer** [comment]
Yeah, that sounds laborious. I plan to be ready for v2 by the end of this week. After that, I hope to find time to add more new models and also plot the prior or something for each model. We are not bounded by space as much as McElreath was in the book. Do the models in https://github.com/StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl overlap much with the models in this project?

**Comment by goedman** [comment]
The models are the same models. SR primarily uses quap (early part of the book) and mcmc results to explain modeling approaches (based on the objectives for the model).

**Pull request merged**
