### PR TITLE
Model improvements

### PR DESCRIPTION
**Pull request by trappmartin**
This PR implements a few improvements on how Turing models are written in this package.

I wasn't sure how the model `m8.4t.jl` should look like as I don't know the definition in the book and therefore left it as is.

### CODE REVIEW

**Comment by trappmartin** [comment]
Often cases the acceptance probability for NUTS is very high (sometimes 0.95) and I'm not sure this intentionally. I have reduced it in most cases to 0.65, which still gives reliable results.

**Comment by torkar** [comment]
Martin, `m8.4` simply shows an example of two parameters $\alpha_1$ and $\alpha_2$ that cannot be identified. Only the sum can be identified (which is 0).
```{r}
m8.4 <- map2stan( 
   alist(
      y ~ dnorm( mu , sigma ) , 
      mu <- a1 + a2 ,
      sigma ~ dcauchy( 0 , 1 )
)
```
i.e., it provides an example where chains don't mix well :)

**Comment by goedman** [comment]
I added the plot figure to the repo clearly showing the behavior Richard mentions. In earlier chapters there are several similar examples (these mostly didn't end up in the model reference repositories though).

**Comment by torkar** [comment]
Thanks, Rob. The plots look awful, as they should :)

**Comment by trappmartin** [comment]
Nice!

**Pull request merged**
