### PR TITLE
Correct and clean up m4.2

### PR DESCRIPTION
**Pull request by karajan9**
Most importantly switch `x` and `y` in the model definition so the model works correctly.
Removed some superfluous converting and simplified DataFrames syntax (I find `df2.weight` easier to read than `df2[:, :weight]` but opinions might differ.

### CODE REVIEW

**Comment by goedman** [comment]
Thanks @karajan9 ! Merged.

**Comment by goedman** [comment]
Hi @karajan9  Can I ask what your goals are? Are you primarily interested in getting the models running or in the StatisticalRethinking added value of regression modeling?

If it is the latter I could set up a StatisticalRethinking branch where we would completely replace Stan by Turing. That is of course a lot more work, lots of mapping of Turing results to DataFrames and plotting, etc. Or we could redefine the contents of TuringModels.jl.

At some point I would go that direction anyway, but right now pretty busy with the causal modeling stuff.

**Comment by karajan9** [comment]
Hi!
I'm not quite sure what you mean by
> Are you primarily interested in getting the models running or in the StatisticalRethinking added value of regression modeling?

?

As I wrote in #18  I'm going through the book, trying to translate the R code (this is where I work with the repo a lot), and working through the exercises.
Since I will be working with the code a lot anyway I'd be happy to help improve this repo, in one way or the other.

**Comment by goedman** [comment]
What I meant was in the StatisticalRethinking.jl repo most effort is on analyzing and working with the results of mcmc simulations while repos such as TuringModels.jl right now just contain a subset of the models.

Ultimately I would like to end up with StatisticalRethinking.jl to provide a set of methods (such as plotcoef, precis, plotbounds, link, quap etc which are useful for all 3 ...Models.jl repos.

From #18 I indeed had the impression you wanted to go beyond just the models. Why don't I send you an invite to the StatisticalRethinkingJulia organization and see where your effort take TuringModels.jl?

**Comment by karajan9** [comment]
Ah yes. So far I'm only up to chapter 3 so I haven't met many of those tools yet. That also means that I'm not really familiar with how things are in that regard in this repo or what worthwhile improvements might be. 

I'm a little worried if I'm able to help because while I have some Julia experience, I have very little experience in Turing, Bayesian modelling, StatisticalRethinking.jl, the book, or developing a package. I'd be happy to try but it might be rocky at first.

I guess before being able to do anything beyond some basic improvements I'd have to grasp the status quo so I get a better understanding what your goals are.
As soon as I manage to set up 2FA I'll look at the invite.

**Comment by ym-han** [comment]
> Ah yes. So far I'm only up to chapter 3 so I haven't met many of those tools yet. That also means that I'm not really familiar with how things are in that regard in this repo or what worthwhile improvements might be.
> 
> I'm a little worried if I'm able to help because while I have some Julia experience, I have very little experience in Turing, Bayesian modelling, StatisticalRethinking.jl, the book, or developing a package. I'd be happy to try but it might be rocky at first.
> 
> I guess before being able to do anything beyond some basic improvements I'd have to grasp the status quo so I get a better understanding what your goals are.
> As soon as I manage to set up 2FA I'll look at the invite.

This is somewhat off-topic, but: karajan, I'm also interested in working through Statistical Rethinking using Turing, as a way to learn both Bayesian statistics and Turing (though I'll probably won't be able to start till late this week or next week). Would you be interested in collaborating / sharing notes / talking about difficult parts or how to adapt it to Turing etc? 

I'm on both slack and Zulip

**Comment by torkar** [comment]
Hi, after @trappmartin updated the models last week, to the latest `Turing` version, most of them are now in good shape. For Edition 2 there are 
1. some new models, and 
2. several of the models have been slightly updated (e.g., new priors etc.)

I asked @goedman before, but Rob, would it be sane to simply make a 2ed branch which can start from the `master` branch?

**Comment by karajan9** [comment]
@ym-han sure, that sounds great! You can find me as Karajan or Jens on Slack or Zulip, feel free to reach out there.

**Comment by trappmartin** [comment]
I think starting a branch of 2ed sounds like a decent plan for now.

**Comment by goedman** [comment]
It's perfectly fine to use a 2ed branch.

I wonder if there is a need to keep the models in the 1st edition of the book around. Thus I'd assumed new priors, new models, etc. would end up in the released version as they become available.

**Comment by torkar** [comment]
Yeah, maybe you're right @goedman, just push for 2nd edition is probably a good option also :)

**Comment by goedman** [comment]
@karajan9 & @ym-han 

Whenever your collaboration/discussions find areas where we can improve either StatisticalRethinking.jl or any of the ...Models.jl repos, please file an issue and/or pull request in the appropriate repo.

My experience with Slack has been that after a few weeks the history was typically gone.

**Comment by karajan9** [comment]
> please file an issue and/or pull request in the appropriate repo

Yes, will do. I have lost too much to the sands of slack to let that happen again :-D

I guess you'd want to discuss something like a roadmap in the issue above? I haven't found one yet but I assume it'd make contributing easier (not just for me).

**Comment by goedman** [comment]
Thank you.

Yes, I'm very interested in feedback on the above idea (repeated now in https://github.com/StatisticalRethinkingJulia/StatisticalRethinking.jl/issues/92#issue-616665714) (if that is what you mean by roadmap).

**Pull request merged**
