### PR TITLE
Rename chains to chns

### LINKED ISSUE #64: Rename chains to chn
In the scripts, the variable `chains` is used all over the place. Unfortunately, `chains` is also exported by `MCMCChains`, which can cause issues like
```
julia> chains = sample(model(a, b), NUTS(0.65), 1000)
ERROR: invalid redefinition of constant chains
```
Thanks to David Widmann for figuring this out (https://github.com/TuringLang/Turing.jl/issues/1529). 

To solve this issue, and avoid problems in the future for us and for users, we would be better of renaming the variables to `chn` or `chns` or something.

### PR DESCRIPTION
**Pull request by BobinMathew**
Issue #64

I renamed all chains to chns except for chains inside comments/documentation(eg:-'''content''') and Chains(with uppercase 'C').

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Thanks for your work. However, CI fails so something is wrong. Did you change the occurrence in utils.jl too?

**Comment by BobinMathew** [comment]
No, I only made changes in the files inside scripts
I didn't  change anything in utils.jl

**Comment by BobinMathew** [comment]
The warning occurred at this file 👇
'_models/partial-pooling-estimates.md_'

this leads to '_scripts/partial-pooling-estimates.jl_'

**Comment by rikhuijzer** [comment]
I see many more errors too. There is also an occurrence of chains in utils.jl used for \defaultoutput. See function lx_defaultoutput

**Comment by BobinMathew** [comment]
> I see many more errors too. There is also an occurrence of chains in utils.jl used for \defaultoutput. See function lx_defaultoutput

yes I see it, I have to change chains to chns in them too right?

**Comment by rikhuijzer** [comment]
> yes I see it, I have to change chains to chns in them too right?

Yes, if you look at the source code for a file and the output on the website, you see why. To test locally whether everything works again go into your cloned version of this repository and run 
```
julia --project -ie 'using Franklin; Franklin.serve()'
```
(This takes 20 minutes on the first run, but of course you can just do other things in the meantime.) If that doesn't show any errors, then the CI job will probably also pass and I can merge your changes.

**Pull request merged**
