### PR TITLE
Convert all existing models to Literate

### PR DESCRIPTION
**Pull request by rikhuijzer**
After this PR, all files in `models` contain `\literate{/scripts/...}`.

### CODE REVIEW

**Review by goedman — APPROVED** [review]
Difficult to review in this format. I prefer to check it using the website.

**Comment by rikhuijzer** [comment]
> Difficult to review in this format. I prefer to check it using the website.

~~As far as I know, there are a few ways to make that possible:~~
1. ~~I push directly to master and we fix from there. This might be a bit unwieldy when, at a later point in time, people start sending in PRs which we have to check.~~
1. ~~In the GitHub Action, push pull requests to a different folder (like PR), so that https://statisticalrethinkingjulia.github.io/TuringModels.jl/PR/ would show the site for the latest pull-request. This option is quite easy to achieve but multiple pull requests will then overlap.~~
1. ~~Like the previous one but send the PRs to different folders in the `gh-pages` branch.~~

~~Usually, Netlify is the best option for showing pull request web pages. However, I think we would run out of build minutes there and I'm not sure whether the build image includes Julia. I've been messing with their build image before and noticed that you don't have sudo permissions.~~

EDIT: In accordance with Occam's Razor, lets just simply fail the build if anything happens when Franklin builds the pages. Then, we only have to inspect the code for strange things and can be assured that the build will succeed after the merge. To be more sure, we can of course always add tests and asserts as always. To view the site locally use
```
julia -ie --project 'using Franklin; Franklin.serve()'
```
and open `http://localhost:8000/` in the browser.

**Comment by rikhuijzer** [comment]
The pull request is unfinished by the way, which I try to indicate with the `Draft` label. I thought it would be easier this way to see what work is in progress.

**Comment by rikhuijzer** [comment]
Related discussions at https://github.com/travis-ci/dpl/issues/991, https://github.com/bids-standard/bids-website/issues/76 and https://github.com/bids-standard/bids-website/issues/81.

**Pull request merged**
